import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer/page'
import Nav from '@/components/nav/page'

export const metadata: Metadata = {
  title: 'Moui',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-main">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
